### ISSUE TITLE
The workers have problems deserializing the object from the calling librairie.

### ISSUE THREAD

**Issue by poquirion** [poquirion/distribute2mpi#10]
```
Traceback (most recent call last):
  File "/home/poquirion/neuropoly/spinalcordtoolbox/scripts/ponyexpress.py", line 496, in <module>
    main()
  File "/home/poquirion/neuropoly/spinalcordtoolbox/scripts/ponyexpress.py", line 489, in main
    worker.exec_pool()
  File "/home/poquirion/neuropoly/spinalcordtoolbox/scripts/ponyexpress.py", line 396, in exec_pool
    the_job = self.icomm.recv(source=0, tag=self.TAG_JOB_TO_WORKER)
  File "MPI/Comm.pyx", line 1192, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:106889)
  File "MPI/msgpickle.pxi", line 292, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:43053)
  File "MPI/msgpickle.pxi", line 143, in mpi4py.MPI.Pickle.load (src/mpi4py.MPI.c:41248)
AttributeError: 'module' object has no attribute 'function_launcher'
```
might be a good reading:https://conference.scipy.org/scipy2014/schedule/presentation/1684/

**Comment by poquirion** [comment]
Providing the full function "module path" to ponyexpress fixes that. We should not have t do that.

**Comment by poquirion** [comment]
The __init__.py module of the package was to funcky for pickel or dill it seams. Moving to a pure module paradigme for the time being solved the problem. Also forcing dill.
